const routes = {
  landingPage: "/",
  login: "/login",
  home: "/home",
  dashboard: "/dashboard",
  rough: "/rough",
  office: "/office",
  factory: "/factory",  
  roughsubpacket: "/rough/subpacket/:id",
  officesubpacket: "/office/subpacket/:id",
  factorysubpacket: "/factory/subpacket/:id",
  officedatasheet: "/officesheet",
  factorydatasheet: "/factorysheet",
  order: "/order-summary",
  polishreport: "/polish-report",
  packetreport: "/packet-report",
  costreport: "/cost-report",
  seller: "/seller",
  broker: "/broker",
  buyer: "/buyer",
  employee: "/employee",
  sallary: "/sallary",
  costMaster: "/cost-master",
  settingpage: "/SettingPage",
};

export default routes;
